###############################################################################
#
#   Software to be installed in the main environment
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---

  name: warlock

  channels:
    - conda-forge
    - bioconda

  dependencies:
    - bioconductor-graph>=1.76.0
    - bioconductor-rgraphviz>=2.42.0
    - boost-cpp>=1.74.0
    - compilers>=1.7.0
    - graphviz>=8.0.3
    - jinja2>=3.1.2
    - python>=3.8.0
    - pyyaml>=6.0
    - r-ape>=5.8
    - r-base>=4.0.3
    - r-data.table>=1.15.4
    - r-devtools>=2.4.5
    - r-dplyr>=0.7.0
    - r-ggmuller>=0.5.6
    - r-ggplot2>=3.5.1
    - r-gridextra>=2.3
    - r-lazyeval>=0.2.2
    - r-moments>=0.14.1
    - r-optparse>=1.7.5
    - r-rcolorbrewer>=1.1_3
    - r-readr>=2.1.5
    - r-rlang>=1.1.4
    - r-rvaidememoire>=0.9_83_7
    - r-scales>=1.3.0
    - r-teachingdemos>=2.12.1
    - snakemake>=7.18.2

...
