#!/bin/bash

set -ex

g++ \
resources/demon_model/src/demon.cpp \
-o resources/demon_model/bin/demon \
-I/srv/conda/envs/notebook/include/ \
-lm

chmod +x prepare-environments.sh
bash -c 'CONDA_PREFIX="/srv/conda/envs/notebook" ./prepare-environments.sh'