###############################################################################
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---
name: ci

on: push

jobs:

  pipeline-testruns:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup miniconda & conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 4.7.12
          auto-update-conda: false
          environment-file: environment.yml
          activate-environment: demon-runner
          auto-activate-base: false

      - name: Display all miniconda & env info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Print compiler path (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: which g++

      - name: Print compiler path (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: which clang++

      - name: Compile demon (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: >
            g++ workflow/src/demon.cpp
            -o workflow/bin/demon
            -I/usr/share/miniconda3/envs/demon-runner/include
            -lm

      - name: Compile demon (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: >
            clang++ workflow/src/demon.cpp
            -o workflow/bin/demon
            -I/Users/runner/miniconda3/envs/demon-runner/include
            -lm

      # Run the tests sequentially;
      # This could be parallelized in the CI but setting up conda
      # is expensive; its faster to run the tests one-by-one. 

      - name: Run the pipeline (test1) (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: >
            bash demon-runner.sh
            --configfile tests/test1/config-Ubuntu.yml
            --environment local

      - name: Run the pipeline (test1) (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: >
            bash demon-runner.sh
            --configfile tests/test1/config-macOS.yml
            --environment local

      - name: Run the pipeline (test2) (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: >
            bash demon-runner.sh
            --configfile tests/test2/config-Ubuntu.yml
            --environment local
            --cores 4

      - name: Run the pipeline (test2) (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: >
            bash demon-runner.sh
            --configfile tests/test2/config-macOS.yml
            --environment local
            --cores 4

      - name: Run the pipeline (test3) (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: >
            bash demon-runner.sh
            --configfile tests/test3/config-Ubuntu.yml
            --environment local
            --cores 2

      - name: Run the pipeline (test3) (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: >
            bash demon-runner.sh
            --configfile tests/test3/config-macOS.yml
            --environment local
            --cores 2

...
