###############################################################################
#
#   AUTHOR: Maciej_Bak
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 15-02-2022
#   LICENSE: Apache_2.0
#
###############################################################################
---
name: ci-pipeline

on: push

jobs:

  pipeline-testruns:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup miniconda & conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          channels: conda-forge,defaults
          channel-priority: true
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: warlock
          auto-activate-base: false

      - name: Display all miniconda & env info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Print compiler path (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: which g++

      - name: Print compiler path (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: which clang++

      - name: Compile demon (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: >
            g++ resources/demon_model/src/demon.cpp
            -o resources/demon_model/bin/demon
            -I/usr/share/miniconda3/envs/warlock/include
            -lm

      - name: Compile demon (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: >
            clang++ resources/demon_model/src/demon.cpp
            -o resources/demon_model/bin/demon
            -I/Users/runner/miniconda3/envs/warlock/include
            -lm

      # Run the tests sequentially;
      # This could be parallelized in the CI but setting up conda
      # is expensive; its faster to run the tests one-by-one.

      - name: Run the pipeline (test1) (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: >
            bash warlock.sh
            --configfile tests/test1/config-Ubuntu.yml
            --environment local

      - name: Run the pipeline (test1) (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: >
            bash warlock.sh
            --configfile tests/test1/config-macOS.yml
            --environment local

      - name: Cleanup (test1)
        shell: bash -l {0}
        run: rm -rf tests/test1/output

      - name: Run the pipeline (test2) (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: >
            bash warlock.sh
            --configfile tests/test2/config-Ubuntu.yml
            --environment local
            --cores 4

      - name: Run the pipeline (test2) (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: >
            bash warlock.sh
            --configfile tests/test2/config-macOS.yml
            --environment local
            --cores 4

      - name: Cleanup (test2)
        shell: bash -l {0}
        run: rm -rf tests/test2/output

      - name: Run the pipeline (test3) (Ubuntu)
        shell: bash -l {0}
        if: matrix.os == 'ubuntu-20.04'
        run: >
            bash warlock.sh
            --configfile tests/test3/config-Ubuntu.yml
            --environment local
            --cores 2

      - name: Run the pipeline (test3) (macOS)
        shell: bash -l {0}
        if: matrix.os == 'macos-11'
        run: >
            bash warlock.sh
            --configfile tests/test3/config-macOS.yml
            --environment local
            --cores 2

      - name: Cleanup (test3)
        shell: bash -l {0}
        run: rm -rf tests/test3/output
...
